// <auto-generated />
using System;
using AgroVerde.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroVerde.Infrastructure.Migrations
{
    [DbContext(typeof(AgroVerdeDbContext))]
    [Migration("20260927011123_CriarTabelasRebanhoFinanceiro")]
    partial class CriarTabelasRebanhoFinanceiro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AgroVerde.Domain.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brinco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.ControleSanitario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticoTratamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ControlesSanitarios");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Pesagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPesagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Pesagens");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.RegistroReproducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificacaoMacho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrevisaoParto")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("RegistrosReproducao");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Talhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Area")
                        .HasColumnType("REAL")
                        .HasColumnName("area");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("TipoSolo")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_solo");

                    b.HasKey("Id");

                    b.ToTable("talhao", (string)null);
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.TransacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("TransacoesFinanceiras");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Vacinacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeVacina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaDose")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Vacinacoes");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.ControleSanitario", b =>
                {
                    b.HasOne("AgroVerde.Domain.Entities.Animal", "Animal")
                        .WithMany("ControlesSanitarios")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Pesagem", b =>
                {
                    b.HasOne("AgroVerde.Domain.Entities.Animal", "Animal")
                        .WithMany("Pesagens")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.RegistroReproducao", b =>
                {
                    b.HasOne("AgroVerde.Domain.Entities.Animal", "Animal")
                        .WithMany("Reproducoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.TransacaoFinanceira", b =>
                {
                    b.HasOne("AgroVerde.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Vacinacao", b =>
                {
                    b.HasOne("AgroVerde.Domain.Entities.Animal", "Animal")
                        .WithMany("Vacinacoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Animal", b =>
                {
                    b.Navigation("ControlesSanitarios");

                    b.Navigation("Pesagens");

                    b.Navigation("Reproducoes");

                    b.Navigation("Vacinacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
