// <auto-generated />
using AgroVerde.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroVerde.Infrastructure.Migrations
{
    [DbContext(typeof(AgroVerdeDbContext))]
    [Migration("20260926192900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AgroVerde.Domain.Entities.Talhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Area")
                        .HasColumnType("REAL")
                        .HasColumnName("area");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("TipoSolo")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_solo");

                    b.HasKey("Id");

                    b.ToTable("talhao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
