// <auto-generated />
using System;
using AgroVerde.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroVerde.Infrastructure.Migrations
{
    [DbContext(typeof(AgroVerdeDbContext))]
    [Migration("20260927183229_AddSafra")]
    partial class AddSafra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AgroVerde.Domain.Entities.Safra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cultura");

                    b.Property<string>("DataColheitaPrevista")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_colheita_prevista");

                    b.Property<string>("DataColheitaReal")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_colheita_real");

                    b.Property<string>("DataPlantio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_plantio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<double?>("ProducaoEstimada")
                        .HasColumnType("REAL")
                        .HasColumnName("producao_estimada");

                    b.Property<double?>("ProducaoObtida")
                        .HasColumnType("REAL")
                        .HasColumnName("producao_obtida");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TalhaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("talhao_id");

                    b.Property<string>("Variedade")
                        .HasColumnType("TEXT")
                        .HasColumnName("variedade");

                    b.HasKey("Id");

                    b.ToTable("safra", (string)null);
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Talhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Area")
                        .HasColumnType("REAL")
                        .HasColumnName("area");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("TipoSolo")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_solo");

                    b.HasKey("Id");

                    b.ToTable("talhao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
