// <auto-generated />
using System;
using AgroVerde.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroVerde.Infrastructure.Migrations
{
    [DbContext(typeof(AgroVerdeDbContext))]
    [Migration("20260927235449_AddEstoque")]
    partial class AddEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AgroVerde.Domain.Entities.EstoqueInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DataMovimentacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_movimentacao");

                    b.Property<int>("EstoqueItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estoque_item_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<double>("QuantidadeUtilizada")
                        .HasColumnType("REAL")
                        .HasColumnName("quantidade_utilizada");

                    b.Property<int>("SafraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("safra_id");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("REAL")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("estoque_insumo", (string)null);
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.EstoqueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categoria");

                    b.Property<double>("EstoqueMinimo")
                        .HasColumnType("REAL")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("TEXT")
                        .HasColumnName("fornecedor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<double>("PrecoMedioUnitario")
                        .HasColumnType("REAL")
                        .HasColumnName("preco_medio_unitario");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propriedade_id");

                    b.Property<double>("QuantidadeAtual")
                        .HasColumnType("REAL")
                        .HasColumnName("quantidade_atual");

                    b.Property<double>("QuantidadeInicial")
                        .HasColumnType("REAL")
                        .HasColumnName("quantidade_inicial");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id");

                    b.ToTable("estoque_item", (string)null);
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Safra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cultura");

                    b.Property<string>("DataColheitaPrevista")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_colheita_prevista");

                    b.Property<string>("DataColheitaReal")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_colheita_real");

                    b.Property<string>("DataPlantio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_plantio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<double?>("ProducaoEstimada")
                        .HasColumnType("REAL")
                        .HasColumnName("producao_estimada");

                    b.Property<double?>("ProducaoObtida")
                        .HasColumnType("REAL")
                        .HasColumnName("producao_obtida");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("TalhaoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("talhao_id");

                    b.Property<string>("Variedade")
                        .HasColumnType("TEXT")
                        .HasColumnName("variedade");

                    b.HasKey("Id");

                    b.ToTable("safra", (string)null);
                });

            modelBuilder.Entity("AgroVerde.Domain.Entities.Talhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("Area")
                        .HasColumnType("REAL")
                        .HasColumnName("area");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("TipoSolo")
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_solo");

                    b.HasKey("Id");

                    b.ToTable("talhao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
